### ISSUE TITLE
TravisCI build Error

### ISSUE THREAD

**Issue by raja-M1993** [forcedotcom/sfdx-travisci#10]
I have got an error.when I build a job
![travisci](https://user-images.githubusercontent.com/26565349/27862162-98850cee-61a1-11e7-81ca-221b1855b727.PNG)
can you please tell me.how to resolve the probelm
Thanks

**Comment by iamjayholt** [comment]
In the trailhead notes, it says to delete that line from the file before pushing. It is Step 2 under Encrypt Your Secrets.

**Comment by raja-M1993** [comment]
thank you @iamjayholt 
It is working fine and the build also succeed
