### ISSUE TITLE
Build Error - YAML Line 16

### ISSUE THREAD

**Issue by iamjayholt** [forcedotcom/sfdx-travisci#11]
<img width="1107" alt="screen shot 2017-07-05 at 4 06 16 pm" src="https://user-images.githubusercontent.com/5420226/27882769-fbc6753c-619b-11e7-81bd-f3774511e6da.png">

My builds keep failing, and I am not sure how to fix this. I tried changing server.key to server.key.enc since that is the file in the assets folder, but both ways failed.

**Comment by dcarroll** [comment]
You should not publish server.key to github.  The yaml file decrypts server.key.enc to server.key on the build system, which is then destroyed after the build completes.

**Comment by sarita1510** [comment]
i think you should give your own consumer key and user name for the dev hub org and try.
let me know if that helps

**Comment by bartyzelm** [comment]
![travis-ci](https://user-images.githubusercontent.com/23452122/53628459-5df2a280-3c0b-11e9-85e2-c0d42e5812b1.JPG)

In git I have only server.key.enc. I declared CONSUMERKEY and USERNAME in Travis as variables, I Authorised user on my pc using sfdx Cli 

Any Ideas ?

**Comment by tnoonan-salesforce** [comment]
I've gotten that exact same error before. It was because of bug in Node 10.12. Try upgrading node js to the LTS version 10.15.2..
