### ISSUE TITLE
"The callback URL provided is not valid" on JWT or SFDXURL Auth

### ISSUE THREAD

**Issue by jpmonette** [forcedotcom/sfdx-travisci#12]
I've been trying to login from Travis using the `sfdx force:auth:sfdxurl:store` command instead. However, when comes the time to spin-up a scratchorg, I am getting that error message:

> ERROR running force:org:create:  The callback URL provided is not valid.

Any clue what can cause this / how it can be resolved?

**Comment by jpmonette** [comment]
Out of curiousity, I decided to try as well with the JWT token and this is what I get after a successful login in Travis CI.

<img width="824" alt="capture d ecran 2017-07-07 a 13 04 04" src="https://user-images.githubusercontent.com/1114325/27957130-d74e736a-6314-11e7-8659-33ed8241e628.png">

Not too sure where I am suppose to set up a callback URL. Any clue?

**Comment by amphro** [comment]
Usually you get that if you are using a custom connected app with an invalid callback URL. I'm assuming you are also using a custom connected app in the sfdxurl:store as well?

More specifically, the callback url on the connected app should be `http://localhost:1717/OauthRedirect`

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_connected_app.htm

**Comment by jpmonette** [comment]
@amphro Was successful with this. Thanks so much!

**Comment by Lee-Xiao-Long** [comment]
To save anyone some potential hair-pulling, the OAuth callback URL for your custom connected app is **case-sensitive**, at least for the purposes of the `force:org:create` command :-|

So even though you will be able to authenticate through a custom connected app with a callback URL such as `http://localhost:1717/OAuthRedirect`-- using both `force:auth:web:login` and `force:auth:jwt:grant` -- you will get that invalid Callback URL error when next trying to spin up a scratch org.

`http://localhost:1717/OauthRedirect` it must be.  That little `a` was a big pain in the `A`.
