### ISSUE TITLE
travisci build error

### ISSUE THREAD

**Issue by lintaotan** [forcedotcom/sfdx-travisci#161]
the log like this:

$ openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv -in assets/server.key.enc -out assets/server.key -d
bad decrypt
140707428578968:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:evp_enc.c:518:
The command "openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv -in assets/server.key.enc -out assets/server.key -d" failed and exited with 1 during .
Your build has been stopped.
[log.txt](https://github.com/forcedotcom/sfdx-travisci/files/5534879/log.txt)

**Comment by lintaotan** [comment]
Duplicate of #

**Comment by Excalibur212** [comment]
@lintaotan Receiving the same error... What was the fix?
